### ISSUE TITLE
Multiple detection with new Mediapipe Palm Detect model capability

### ISSUE THREAD

**Issue by potkpot** [keijiro/HandPoseBarracuda#12]
I tried to use new model of Palm Detection [models](https://github.com/google/mediapipe/tree/master/mediapipe/modules/palm_detection) from this [post](https://blog.tensorflow.org/2021/11/3D-handpose.html)
to add multiple hand detect. So i have some trouble
- After convetration model Barracuda can't use some layers [Here is converted](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/033_Hand_Detection_and_Tracking/21_new_full_lite)
- Postprocess layers difficult to customize to add non maximum suppression algorithm

So did you use costom models(without custom layers) to use in Barracuda?
Which simplest way to add mutliple detect with non max sorting feature?

**Comment by keijiro** [comment]
> So did you use costom models(without custom layers) to use in Barracuda?

Yes.

> Which simplest way to add mutliple detect with non max sorting feature?

For example, I removed an NMS layer and add a custom postprocess shader for the MLSD model.

https://github.com/keijiro/MlsdBarracuda

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
