### ISSUE TITLE
Unity Bolt Friendly Implementation Added (Enhancement) 

### ISSUE THREAD

**Issue by TKTSWalker** [keijiro/HandPoseBarracuda#13]
I don't do to well with programming so i've been adding Unity Bolt based additions to the system! For example, you can directly reference the points using Unity Bolt much easier than compared to the script, although I have been struggling with getting the response from the Pipeline so I will be adding a script for that eventually. Another thing I want to add is Unity automatically creating and destroying instances of hand tracking depending on the amount of hands in the scene! I'll update this thread as I continue working!

**Comment by keijiro** [comment]
Thanks for letting me know it. It sounds a great project.

I'm closing this issue ticket as the topic is not actual "issue", but please feel free to keep updating it if you want. It would be useful for those who are not familiar with the C# language.
