### ISSUE TITLE
How to install HandPoseBarracuda

### ISSUE THREAD

**Issue by NachoSaanchez** [keijiro/HandPoseBarracuda#14]

**Comment by NachoSaanchez** [comment]
Hello, I've try a bit in Unity and it works very well but i don't know how to use it for a simple game. Unity just show my real hand with the nodes, not a representation as a model in a scene or something similar

**Comment by keijiro** [comment]
> not a representation as a model in a scene or something similar

You have to develop a method to inverse-project the node points to the 3D world space with hand joint constraints. I didn't it in this project because I'd like to keep this sample project as simple as possible.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
