### ISSUE TITLE
How to get cartesian coordinates of hand?

### ISSUE THREAD

**Issue by Arham-Aalam** [keijiro/HandPoseBarracuda#2]
It there a way to access real world coordinates of the predicted landmarks, I try to get them using this method:
```
Debug.Log("INDEX-> " + _pipeline.GetKeyPoint(HandPipeline.KeyPoint.Index4));
Debug.Log("thumb-> " + _pipeline.GetKeyPoint(HandPipeline.KeyPoint.Thumb4));
```
But it is giving me something like this:
```
INDEX-> (0.2, 0.3, 1.0)
thumb-> (0.2, 0.5, 1.0)
```

**Comment by keijiro** [comment]
The hand pose pipeline only returns screen-space coordinates. If you want depth (z-axis) values, you have to integrate another solution like a depth estimator.

**Comment by Arham-Aalam** [comment]
Is there a way to calculate angle between a center point of a ball in a scene and index finger coordinate? It seems difficult to calculate it with screen-space coordinates. Basically I want to calculate theta shown in image, Any hint?
![image](https://user-images.githubusercontent.com/23229365/127650833-1fcbeada-2fee-4dc0-ab88-95c14de33d20.png)

**Comment by keijiro** [comment]
Please understand that this issue tracker is dedicated for solving bugs found in the HandPoseBarracuda package. I'd recommend using the Unity forum or other communities to solve these kinds of general math problems.

**Comment by Arham-Aalam** [comment]
Thanks @keijiro for quick reply, I'm quite new to unity and both of these objects(hand, ball) giving me different types of coordinates which doesn't make sense if I apply angle measurement formula, Anyway I'll try to get help from other forums.
Thanks!
