### ISSUE TITLE
Any way to find out if MediaPipe is currently detecting a Hand Pose?

### ISSUE THREAD

**Issue by thePostFuturist** [keijiro/HandPoseBarracuda#20]

**Comment by keijiro** [comment]
yes https://github.com/keijiro/BlazePalmBarracuda/blob/main/Packages/jp.keijiro.mediapipe.blazepalm/Runtime/PalmDetector.cs#L33

**Comment by thePostFuturist** [comment]
Hey that was lighting fast. Thanks, Keijiro. There is a nuance though. detections.Length returns as 0 if a part of the hand is obstructed (for example if my palm was outside the camera frustum). A confidence score would be nice just to see if I'm catching anything, but thanks for your pointer to begin with.

Here's my logic:

```
    void Start()
    {
        _pipeline = new HandPipeline(_resources);
        _palmDetector = new PalmDetector(_resources.blazePalm);
    }
    void LateUpdate()
    {
        var detections = _palmDetector.Detections;
        bool isHandDetected = detections.Length > 0;

        if (isHandDetected)
        {
            Debug.Log(1);
        }
        else
        {
            Debug.Log(0);
        }
   }
   
```
