### ISSUE TITLE
How to adjust the scale and position of skeleton hand

### ISSUE THREAD

**Issue by GFTQ** [keijiro/HandPoseBarracuda#3]
Dear @keijiro, the skeleton hand seems to be only located at (0,0,0) in unity with a fixed scale size. I just want to adjust the scale and position of the virtual skeleton hand. Please can you inform me? Thank you.

**Comment by keijiro** [comment]
See HandAnimator.cs

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by GFTQ** [comment]
Thank you for your quick response. Sorry to bother you again, I am quite unfamiliar with the hand resize and relocation. As you mentioned HandAnimator.cs, I just check the script and find that both position and scale parameters are private, and they can not be set parameters with an interface.
![image](https://user-images.githubusercontent.com/23331090/129435527-bcdc4acf-81a5-43d7-b11b-bcf7fc9c11a1.png)
The issue I got is to adjust the hand in my preset scene, like this
![image](https://user-images.githubusercontent.com/23331090/129435706-7dbdb66a-b87e-491d-a9e6-98668c117bd4.png)

**Comment by keijiro** [comment]
This is an open source project. You can edit it as you want.
