### ISSUE TITLE
How to add support for multiple hands

### ISSUE THREAD

**Issue by noble-man** [keijiro/HandPoseBarracuda#4]
Hello,

Thanks for sharing your work.
How would you go about adding support for multiple hands?
Can it be done simply by replacing the ONNX model with a "multi-hand" one?

Regards,

**Comment by keijiro** [comment]
There is no such thing as a "multi-hand" model. Or did you find one?

[BlazePalm](https://github.com/keijiro/BlazePalmBarracuda) (first-stage hand detector) supports multiple hands, so you can implement multi-hand support by running the [hand landmark detector](https://github.com/keijiro/HandLandmarkBarracuda) (second-stage detector) multiple times.

The current implementation only runs the hand landmark detector with a hand with the highest confidence score, so it only tracks a single hand.

Even though you can add multi-hand support by modifying the pipeline, it's not an easy task. You have to implement a kind of [object tracking algorithm](https://blog.netcetera.com/object-detection-and-tracking-in-2020-f10fb6ff9af3) to prevent random jump/swapping.

The main aim of this repository is to show the most basic implementation of the GPU-based hand detection pipeline, so I avoid introducing extra complexity with multi-hand tracking.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by redHurt96** [comment]
So if i don't need a very high accuracy, can i add a multi-hand support by running the landmark detector with all hands with high enough score? Or it much mory complicate then i think?)

**Comment by keijiro** [comment]
It would swap your right/left hand randomly. You have to filter them out.
