### ISSUE TITLE
No hand detected and figure out left or right?

### ISSUE THREAD

**Issue by codesafe** [keijiro/HandPoseBarracuda#5]
Hello.
Thanks for your sharing.
I have 2 questions. 
1. How can I know no hand on camera? ( Can't detect hand or something like that. )
2. I want know how to figure out left hand or right hand.

Regards.

**Comment by keijiro** [comment]
> 1. How can I know no hand on camera? ( Can't detect hand or something like that. )

https://github.com/keijiro/BlazePalmBarracuda/blob/main/Packages/jp.keijiro.mediapipe.blazepalm/Script/PalmDetector.cs#L26

> 2. I want know how to figure out left hand or right hand.

https://github.com/keijiro/HandLandmarkBarracuda/blob/main/Packages/jp.keijiro.mediapipe.handlandmark/Script/HandLandmarkDetectorPublic.cs#L66

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen it for further problems.

**Comment by jerryComo** [comment]
Hi - regarding detecting left or right hand  - I'm tracing out Handedness as indicated above (and also Score) and I cannot determine whether it is a left or a right hand from the results.  The mediapipe hands page mentions a label variable which doesn't seem to be public. Is there a way I can expose this ? 

"MULTI_HANDEDNESS
Collection of handedness of the detected/tracked hands (i.e. is it a left or right hand). Each hand is composed of label and score. label is a string of value either "Left" or "Right". score is the estimated probability of the predicted handedness and is always greater than or equal to 0.5 (and the opposite handedness has an estimated probability of 1 - score)."

**Comment by keijiro** [comment]
@jerryComo 
https://github.com/keijiro/HandLandmarkBarracuda/blob/main/Packages/jp.keijiro.mediapipe.handlandmark/Script/HandLandmarkDetectorPublic.cs#L66

**Comment by jerryComo** [comment]
Hi - thanks for the reply - When I trace this Handedness value out I get values between -1 and 0 regardless of which hand I am using. Is this right ?
