### ISSUE TITLE
Error caused by the Graphics API when building on Android.

### ISSUE THREAD

**Issue by noble-man** [keijiro/HandPoseBarracuda#6]
Hello, 

When I try to build and run a test scene on Android I get this warning in Unity:
`Shader warning in 'Conv2dA_NCHW': signed/unsigned mismatch, unsigned assumed at kernel Conv2DKernel1x1_StrictC16K64_T16x16_R4x4_NCHW `

And the application keeps crashing on Android with this error:
`ERROR: Unable to link compute shader: Conv2dA_NHWC.Conv2DKernelKxK_T16x16_R4x4_NHWC`

If I switch Graphics API to "Vulkan" it works, but I need to use "OpenGLES3".

Could you help me with that?

**Comment by keijiro** [comment]
> If I switch Graphics API to "Vulkan" it works, but I need to use "OpenGLES3".

No, you can't because Barracuda doesn't support OpenGLES on Android.

https://docs.unity3d.com/Packages/com.unity.barracuda@2.1/manual/SupportedPlatforms.html?q=vulkan

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
