### ISSUE TITLE
Optimize on mobile

### ISSUE THREAD

**Issue by vinpix** [keijiro/HandPoseBarracuda#7]
Thank you for this great project, but is there any way to optimize it on mobile. I tried lowering the resolution, but it's still the same

**Comment by keijiro** [comment]
You can't optimize it by changing the resolution because the input resolution of those neural network models are fixed. You'll just get worse quality without any performance gain.

The only thing you can try is CPU inference. Some mobile GPUs are not good at neural network inference, so possibly it's better to use CPU cores.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by vinpix** [comment]
can you please help me how to change the calculation from GPU to CPU ?

**Comment by keijiro** [comment]
https://docs.unity3d.com/Packages/com.unity.barracuda@2.1/api/Unity.Barracuda.WorkerFactory.Device.html

**Comment by vinpix** [comment]
Thanks for the docs, when I change GPU to CPU the frame rate doubles which is really amazing, but the problem is I can only change from GPU to CPU at PalmDetector.cs, but it gives error "specified cast is not valid" in Utilities.PeekOutputBuffer when I switch to CPU at HandLandmarkDetector.cs. my question is is it possible for me to move the calculation to CPU in HandLandmarkDetector.cs

**Comment by keijiro** [comment]
> "specified cast is not valid"

This is not clear information. Could you copy-paste the entire error message?

**Comment by vinpix** [comment]
Yea sure

InvalidCastException: Specified cast is not valid.
MediaPipe.HandLandmark.IWorkerExtensions.PeekOutputBuffer (Unity.Barracuda.IWorker worker, System.String name) (at Packages/jp.keijiro.mediapipe.handlandmark@1.0.1/Script/Internal/Utilities.cs:10)
MediaPipe.HandLandmark.HandLandmarkDetector.RunModel (UnityEngine.ComputeBuffer input) (at Packages/jp.keijiro.mediapipe.handlandmark@1.0.1/Script/HandLandmarkDetector.cs:61)
MediaPipe.HandLandmark.HandLandmarkDetector.ProcessImage (UnityEngine.ComputeBuffer buffer) (at Packages/jp.keijiro.mediapipe.handlandmark@1.0.1/Script/HandLandmarkDetectorPublic.cs:40)
MediaPipe.HandPose.HandPipeline.RunPipeline (UnityEngine.Texture input) (at Assets/HandPose/Script/HandPipeline_Process.cs:44)
MediaPipe.HandPose.HandPipeline.ProcessImage (UnityEngine.Texture image) (at Assets/HandPose/Script/HandPipeline_Public.cs:57)
MediaPipe.HandPose.HandVisualizer.LateUpdate () (at Assets/Test/Script/HandVisualizer.cs:61)

**Comment by vinpix** [comment]
<img width="1153" alt="Screen Shot 2021-09-09 at 13 29 29" src="https://user-images.githubusercontent.com/76024897/132634493-8b013aff-38c0-4a47-ad52-ad7f3a2c9936.png">

**Comment by vinpix** [comment]
the HandLandmarkDetector.cs it works fine with GPU but not CPU

**Comment by keijiro** [comment]
The error message is pointing at `Packages/jp.keijiro.mediapipe.handlandmark@1.0.1/Script/Internal/Utilities.cs:10`, but it's not relevant to your modification. Did you modify it? If so, try reverting it.

**Comment by vinpix** [comment]
<img width="840" alt="Screen Shot 2021-09-09 at 14 02 55" src="https://user-images.githubusercontent.com/76024897/132638577-e3ece2e4-26fc-4c94-8155-a42d18d3aef8.png">

No it's still the same, I just align the lines for readability

**Comment by keijiro** [comment]
Aha, I see. I assumed that the worker runs on GPU and it returns `ComputeTensorData`. However, you changed it to CPU, so now it returns `BurstTensorData` or something like that.

You have to manually convert it into `ComputeBuffer`. I'm not sure how it should be implemented, though.

**Comment by vinpix** [comment]
thanks for your guidance, it took a while but now i can fully switch to CPU and and the frame rate has increased significantly

**Comment by keijiro** [comment]
Thanks for the feedback. I'll consider adding CPU support to my Barracuda projects.

**Comment by codesafe** [comment]
Hello.
I am suffering from poor performance on mobile. 
Any advice or any sample code is welcome to modify the code to make Barracuda use the CPU.
Thanks.

**Comment by manaspalaparthi** [comment]
hi @vinpix, thats great to hear I'm facing the same problem, can you please guide me to convert GPU to CPU for hand landmarkdetection.

and thank you @keijiro for this amazing project! 
> thanks for your guidance, it took a while but now i can fully switch to CPU and and the frame rate has increased significantly

**Comment by kapupararavi** [comment]
The files described in the HandPoseBarracuda are not available in this project. But, I have made changes in ResourceSet.cs and SegmentationFilter.cs as below. Still I am having lag in my android device.
![image_2021_11_10T11_59_27_395Z](https://user-images.githubusercontent.com/40574114/141109261-4a6f6332-3fda-4470-869e-76b263905425.png)
![image_2021_11_10T12_00_28_643Z](https://user-images.githubusercontent.com/40574114/141109388-6a328b4b-f10f-4650-a54e-5255f4dee038.png)

![image_2021_11_10T12_01_25_379Z](https://user-images.githubusercontent.com/40574114/141109512-3f0720f1-1470-4a8d-be34-97714c753fde.png)
