### ISSUE TITLE
Poor performance on mobile

### ISSUE THREAD

**Issue by codesafe** [keijiro/HandPoseBarracuda#8]
Hello.
I am suffering from poor performance on mobile.
Do you have any advice or sample code to use CPU?
Regards.

**Comment by keijiro** [comment]
First of all, please check #7.

Unfortunately, it needs total reimplementation of pre/post-processing for further optimization, so it's hard to provide a simple advice -- It would end up saying "rewrite them all".

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
