### ISSUE TITLE
screen-to-world-space projector for 3D applications

### ISSUE THREAD

**Issue by GMAGD** [keijiro/HandPoseBarracuda#9]
Hi, i need help for screen-to-world-space projector for and AR app 

Can someone guide me how to implement it ? 

thank you :)

**Comment by keijiro** [comment]
You have to implement a method that estimates the distance of the hand from the camera. There is no single best solution for it -- I think you have to invent a solution in some way -- like calculating depth using a fixed palm size, calculating face depth using [an iris size](https://google.github.io/mediapipe/solutions/iris.html) and applying it as hand depth, etc.

**Comment by keijiro** [comment]
I'm closing this issue now because I have no firm idea about it. Please feel free to reopen it for further problems.
